version: 0.2

env:
  variables:
    GITHUB_USER: ${GITHUB_USER}
    GITHUB_TOKEN: ${GITHUB_TOKEN}
    BASE_URL: ${BASE_URL}
    CLINICAL_USERNAME: ${CLINICAL_USERNAME}
    CLINICAL_PASSWORD: ${CLINICAL_PASSWORD}
    CLINICAL_API_KEY: ${CLINICAL_API_KEY}
    CONSUMER_USERNAME: ${CONSUMER_USERNAME}
    CONSUMER_PASSWORD: ${CONSUMER_PASSWORD}
    CONSUMER_API_KEY: ${CONSUMER_API_KEY}
    SIGMA_PROTOCOLS_URL: ${SIGMA_PROTOCOLS_URL}
    SIGMA_REPORT_URL: ${SIGMA_REPORT_URL}
    SIGMA_REPORT_LOGS_URL: ${SIGMA_REPORT_LOGS_URL}

phases:
  pre_build:
    commands:
      - echo Logging into ECR...
      - aws --version
      - AWS_ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | cut -f5 -d ':')
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/streamlit_epoch_generator-dev
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - export DOCKER_BUILDKIT=1
      - export COMPOSE_DOCKER_CLI_BUILD=1
  build:
    commands:
      - echo Build started on `date`
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:latest \
          --build-arg GITHUB_USER=$GITHUB_USER \
          --build-arg GITHUB_TOKEN=$GITHUB_TOKEN \
          --build-arg BASE_URL=$BASE_URL \
          --build-arg CLINICAL_USERNAME=$CLINICAL_USERNAME \
          --build-arg CLINICAL_PASSWORD=$CLINICAL_PASSWORD \
          --build-arg CLINICAL_API_KEY=$CLINICAL_API_KEY \
          --build-arg CONSUMER_USERNAME=$CONSUMER_USERNAME \
          --build-arg CONSUMER_PASSWORD=$CONSUMER_PASSWORD \
          --build-arg CONSUMER_API_KEY=$CONSUMER_API_KEY \
          --build-arg SIGMA_PROTOCOLS_URL=$SIGMA_PROTOCOLS_URL \
          --build-arg SIGMA_REPORT_URL=$SIGMA_REPORT_URL \
          --build-arg SIGMA_REPORT_LOGS_URL=$SIGMA_REPORT_LOGS_URL \
          .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG

artifacts:
  files:
    - '**/*'
