[tool.poetry]
name = "eeg-plot-streamlit-app"
version = "1.4.1"
description = "EEG plot generator"
authors = ["Luis Camargo <lcamargo@waveneuro.com>"]
license = "Proprietary"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
streamlit = "^1.33.0"
mywaveanalytics = {git = "https://github.com/waveneuroscience/MyWaveAnalytics.git"}
plotly = "^5.22.0"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
